### ISSUE TITLE
Implementar Transformações com Apache Spark.

### ISSUE THREAD

**Issue by lucasfm20** [lucasfm20/ProjetoFinal_EngenhariaDeDados#4]
Realizar transformações de dados nas camadas Bronze e Silver, utilizando Apache Spark para limpeza e enriquecimento dos dados.

-Implementar transformações para limpeza de dados.
-Aplicar regras de enriquecimento, agregação.

**Comment by Jvbrogni** [comment]
Transformações realizadas, as camadas kanding, bronze e silver estão prontas.
