### ISSUE TITLE
Criar Tabela OBT na Camada Gold

### ISSUE THREAD

**Issue by lucasfm20** [lucasfm20/ProjetoFinal_EngenhariaDeDados#5]
Estruturar os dados na camada Gold em um modelo dimensional para facilitar a análise.

-Definir dimensões e fatos.
-Implementar o modelo utilizando Delta Lake ou Apache Iceberg.

**Comment by Jvbrogni** [comment]
Atualmente a camada gold está estagnada a dois dias, os valores da silver foram movidos e tratados, a tabela OBT foi criada, porém ainda não consegui fazer a inserção dos valores dentro dela.

**Comment by Jvbrogni** [comment]
Enfim, consegui inserir os valores dentro da tabela.
