### ISSUE TITLE
Desenvolver Dashboard de KPIs e Métricas

### ISSUE THREAD

**Issue by lucasfm20** [lucasfm20/ProjetoFinal_EngenhariaDeDados#6]
Criar um dashboard para visualizar KPIs e métricas com base nos dados da camada Gold.

-Definir KPIs relevantes para o projeto.
-Configurar visualizações no dashboard ( Power BI).

**Comment by Jvbrogni** [comment]
Desenvolvido com sucesso.  
Será colocado no mkdocs e exibido na apresentação.
