### ISSUE TITLE
 Documentar o Projeto com MkDocs

### ISSUE THREAD

**Issue by lucasfm20** [lucasfm20/ProjetoFinal_EngenhariaDeDados#7]
Escrever a documentação do pipeline usando MkDocs, incluindo instruções para instalação, uso, e detalhes técnicos do projeto.

-Criar estrutura básica da documentação.
-Documentar etapas de configuração, execução e arquitetura.

**Comment by Jotas-V** [comment]
Mkdocs documentado até onde foi realizado o trabalho.
